module.exports = {
    WIDTH: Math.floor(1920),
    // HEIGHT: Math.floor(1058 / 4),
    HEIGHT: Math.floor(1080),
    SCALE: 4,
    MAX_LINES: 65,
    FONT_SIZE: 16,
    ADD: 'ADD',
    REMOVE: 'REMOVE',
    REPLACE: 'REPLACE',
    SELECT: 'SELECT',
    SKIP_TO: 'SKIP_TO',
    MOVE_UP: 'MOVE_UP',
    MOVE_DOWN: 'MOVE_DOWN',
    WAIT: 'WAIT',
    SPEAK: 'SPEAK',
    LINE_DURATION: 'LINE_DURATION',
};
